version: '3'
services:
  database:
    restart: unless-stopped
    image: 'postgres:latest'
    # NOTE: avoid collision with local postgres port
    ports:
      - ${POSTGRES_REDIRECT_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  api:
    restart: unless-stopped
    build:
        context: ./
        dockerfile: api/Dockerfile
    depends_on:
      - database
    ports:
      - '${API_PORT}:${API_PORT}'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
    environment:
      REDWOOD_API_URL: ${API_URL}
      DATABASE_URL: ${DATABASE_URL}
  web:
    restart: unless-stopped
    build:
        context: ./
        dockerfile: web/Dockerfile
    depends_on:
      - api
    ports:
      - '${APP_PORT}:${APP_PORT}'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
