version: '3'
services:
  database:
    restart: on-failure
    image: 'postgres:latest'
    # NOTE: avoid collision with local postgres port
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ekmnhfabjktn16
      POSTGRES_DB: redwood-blog
  api:
    restart: on-failure
    build:
        context: ./
        dockerfile: api/Dockerfile
    depends_on:
      - database
    ports:
      - '8911:8911'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
    environment:
      REDWOOD_API_URL: 'http://0.0.0.0:8911'
      # To connect to a local database, run ifconfig docker0 and update the host for the database.
      # Learn more: https://stackoverflow.com/questions/31249112/allow-docker-container-to-connect-to-a-local-host-postgres-database
      DATABASE_URL: postgres://postgres:ekmnhfabjktn16@database:5432/redwood-blog?connection_limit=1
  web:
    restart: on-failure
    build:
        context: ./
        dockerfile: web/Dockerfile
    depends_on:
      - api
    ports:
      - '8910:8910'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
