name: CI-CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: ./.github/actions/deploy-action
        with:
          branch-name: deploy3







