name: CI-CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-action
        with:
          branch-name: deploy3
          env-file: ${{ secrets.ENV_FILE }}
          gcp-credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp-ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          https-certificate: ${{ secrets.HTTPS_SERTIFICATE }}
          https-key: ${{ secrets.HTTPS_KEY }}
          instance_name: host-server-2
          zone: us-west4-b








